### ISSUE TITLE
The TODO list

### ISSUE THREAD

**Issue by bIgBV** [LucioFranco/clique#31]
These are a list (incomplete) of things still pending until we can spin up a simple 3 node cluster.

* [x] Cut detection
* [x] Surface consensus decision
* [ ] Consensus tests
* [ ] Flesh out membership service
    * [x] On decide
    * [x] Handle probe messages
    * [x] Handle batched alert messages
    * [ ] Subscriptions
    * [x] Metadata manager
* [ ] Cluster event subscriptions
* [ ] Metadata manager
* [ ] Add link cut detector.
